version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations:/migrations:ro
    ports:
      - "55432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./api
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "3000:3000"

  worker:
    build: ./worker
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq

  migrate:
    image: postgres:15
    env_file: .env
    volumes:
      - ./migrations:/migrations:ro
    entrypoint: >
      bash -lc "
      for f in /migrations/*.sql; do
        echo 'Applying' $$f;
        until PGPASSWORD=$$POSTGRES_PASSWORD psql -h db -U $$POSTGRES_USER -d $$POSTGRES_DB -f \"$$f\"; do
          echo 'Retrying' $$f 'in 2s...'; sleep 2;
        done;
      done;
      echo 'Migrations done.';
      "
    depends_on:
      - db

volumes:
  db-data:
